// StudyPlay Static Client-Side Search Index
// Contains metadata for instant search without loading lazy subject modules

export const searchIndex = [
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca452",
    "subjectCode": "CA452",
    "subjectTitle": "Computer Organization & Architecture",
    "unitId": "unit-1",
    "unitNumber": 1,
    "unitTitle": "Unit 1: UNIT 1: DIGITAL LOGIC CIRCUITS — CO1",
    "conceptId": "digital-logic-circuits",
    "conceptTitle": "Digital Logic Circuits",
    "subtitle": "CA452 Unit 1 Concept 1",
    "summary": "Comprehensive study notes covering Digital Logic Circuits with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 4,
    "flashcardCount": 5
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca452",
    "subjectCode": "CA452",
    "subjectTitle": "Computer Organization & Architecture",
    "unitId": "unit-1",
    "unitNumber": 1,
    "unitTitle": "Unit 1: UNIT 1: DIGITAL LOGIC CIRCUITS — CO1",
    "conceptId": "combinational-logic-circuits",
    "conceptTitle": "Combinational Logic Circuits",
    "subtitle": "CA452 Unit 1 Concept 2",
    "summary": "Comprehensive study notes covering Combinational Logic Circuits with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca452",
    "subjectCode": "CA452",
    "subjectTitle": "Computer Organization & Architecture",
    "unitId": "unit-1",
    "unitNumber": 1,
    "unitTitle": "Unit 1: UNIT 1: DIGITAL LOGIC CIRCUITS — CO1",
    "conceptId": "bus-architecture",
    "conceptTitle": "Bus Architecture",
    "subtitle": "CA452 Unit 1 Concept 3",
    "summary": "Comprehensive study notes covering Bus Architecture with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 2,
    "flashcardCount": 3
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca452",
    "subjectCode": "CA452",
    "subjectTitle": "Computer Organization & Architecture",
    "unitId": "unit-2",
    "unitNumber": 2,
    "unitTitle": "Unit 2: UNIT 2: BASIC ORGANIZATION — CO2",
    "conceptId": "basic-organization",
    "conceptTitle": "Basic Organization",
    "subtitle": "CA452 Unit 2 Concept 1",
    "summary": "Comprehensive study notes covering Basic Organization with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 2,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca452",
    "subjectCode": "CA452",
    "subjectTitle": "Computer Organization & Architecture",
    "unitId": "unit-2",
    "unitNumber": 2,
    "unitTitle": "Unit 2: UNIT 2: BASIC ORGANIZATION — CO2",
    "conceptId": "general-register-organization",
    "conceptTitle": "General Register Organization",
    "subtitle": "CA452 Unit 2 Concept 2",
    "summary": "Comprehensive study notes covering General Register Organization with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 2,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca452",
    "subjectCode": "CA452",
    "subjectTitle": "Computer Organization & Architecture",
    "unitId": "unit-2",
    "unitNumber": 2,
    "unitTitle": "Unit 2: UNIT 2: BASIC ORGANIZATION — CO2",
    "conceptId": "memory-hierarchy",
    "conceptTitle": "Memory Hierarchy",
    "subtitle": "CA452 Unit 2 Concept 3",
    "summary": "Comprehensive study notes covering Memory Hierarchy with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 2,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca452",
    "subjectCode": "CA452",
    "subjectTitle": "Computer Organization & Architecture",
    "unitId": "unit-3",
    "unitNumber": 3,
    "unitTitle": "Unit 3: UNIT 3: I/O ORGANIZATION — CO3",
    "conceptId": "io-organization",
    "conceptTitle": "I/O Organization",
    "subtitle": "CA452 Unit 3 Concept 1",
    "summary": "Comprehensive study notes covering I/O Organization with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 2,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca452",
    "subjectCode": "CA452",
    "subjectTitle": "Computer Organization & Architecture",
    "unitId": "unit-3",
    "unitNumber": 3,
    "unitTitle": "Unit 3: UNIT 3: I/O ORGANIZATION — CO3",
    "conceptId": "priority-interrupt",
    "conceptTitle": "Priority Interrupt",
    "subtitle": "CA452 Unit 3 Concept 2",
    "summary": "Comprehensive study notes covering Priority Interrupt with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 2,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca452",
    "subjectCode": "CA452",
    "subjectTitle": "Computer Organization & Architecture",
    "unitId": "unit-3",
    "unitNumber": 3,
    "unitTitle": "Unit 3: UNIT 3: I/O ORGANIZATION — CO3",
    "conceptId": "execution-unit",
    "conceptTitle": "Execution Unit",
    "subtitle": "CA452 Unit 3 Concept 3",
    "summary": "Comprehensive study notes covering Execution Unit with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 2,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca452",
    "subjectCode": "CA452",
    "subjectTitle": "Computer Organization & Architecture",
    "unitId": "unit-4",
    "unitNumber": 4,
    "unitTitle": "Unit 4: UNIT 4: PARALLEL COMPUTING — CO4",
    "conceptId": "introduction-to-parallel-computing",
    "conceptTitle": "Introduction to Parallel Computing",
    "subtitle": "CA452 Unit 4 Concept 1",
    "summary": "Comprehensive study notes covering Introduction to Parallel Computing with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 2,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca452",
    "subjectCode": "CA452",
    "subjectTitle": "Computer Organization & Architecture",
    "unitId": "unit-4",
    "unitNumber": 4,
    "unitTitle": "Unit 4: UNIT 4: PARALLEL COMPUTING — CO4",
    "conceptId": "simd",
    "conceptTitle": "SIMD",
    "subtitle": "CA452 Unit 4 Concept 2",
    "summary": "Comprehensive study notes covering SIMD with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 2,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca452",
    "subjectCode": "CA452",
    "subjectTitle": "Computer Organization & Architecture",
    "unitId": "unit-4",
    "unitNumber": 4,
    "unitTitle": "Unit 4: UNIT 4: PARALLEL COMPUTING — CO4",
    "conceptId": "instruction-pipeline-timing",
    "conceptTitle": "Instruction Pipeline Timing",
    "subtitle": "CA452 Unit 4 Concept 3",
    "summary": "Comprehensive study notes covering Instruction Pipeline Timing with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 2,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca452",
    "subjectCode": "CA452",
    "subjectTitle": "Computer Organization & Architecture",
    "unitId": "unit-5",
    "unitNumber": 5,
    "unitTitle": "Unit 5: UNIT 5: MULTIPROCESSOR — CO5",
    "conceptId": "multiprocessor",
    "conceptTitle": "Multiprocessor",
    "subtitle": "CA452 Unit 5 Concept 1",
    "summary": "Comprehensive study notes covering Multiprocessor with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 2,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca452",
    "subjectCode": "CA452",
    "subjectTitle": "Computer Organization & Architecture",
    "unitId": "unit-5",
    "unitNumber": 5,
    "unitTitle": "Unit 5: UNIT 5: MULTIPROCESSOR — CO5",
    "conceptId": "multistage-interconnection-network",
    "conceptTitle": "Multistage Interconnection Network",
    "subtitle": "CA452 Unit 5 Concept 2",
    "summary": "Comprehensive study notes covering Multistage Interconnection Network with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 2,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca452",
    "subjectCode": "CA452",
    "subjectTitle": "Computer Organization & Architecture",
    "unitId": "unit-5",
    "unitNumber": 5,
    "unitTitle": "Unit 5: UNIT 5: MULTIPROCESSOR — CO5",
    "conceptId": "multiprocessor-scheduling",
    "conceptTitle": "Multiprocessor Scheduling",
    "subtitle": "CA452 Unit 5 Concept 3",
    "summary": "Comprehensive study notes covering Multiprocessor Scheduling with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 2,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca453",
    "subjectCode": "CA453",
    "subjectTitle": "C Programming",
    "unitId": "unit-1",
    "unitNumber": 1,
    "unitTitle": "Unit 1: Computer Fundamentals, Software, Networks & Internet Protocols",
    "conceptId": "computer-fundamentals",
    "conceptTitle": "Computer Fundamentals & Hardware Generations",
    "subtitle": "CA453 Unit 1 Part 1 Academic Mastery",
    "summary": "In-depth analysis of computer fundamentals & hardware generations covering foundational principles, system taxonomies, and architectural design.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca453",
    "subjectCode": "CA453",
    "subjectTitle": "C Programming",
    "unitId": "unit-1",
    "unitNumber": 1,
    "unitTitle": "Unit 1: Computer Fundamentals, Software, Networks & Internet Protocols",
    "conceptId": "software-and-dos",
    "conceptTitle": "Software Classification, Operating Systems & DOS",
    "subtitle": "CA453 Unit 1 Part 2 Academic Mastery",
    "summary": "In-depth analysis of software classification, operating systems & dos covering foundational principles, system taxonomies, and architectural design.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca453",
    "subjectCode": "CA453",
    "subjectTitle": "C Programming",
    "unitId": "unit-1",
    "unitNumber": 1,
    "unitTitle": "Unit 1: Computer Fundamentals, Software, Networks & Internet Protocols",
    "conceptId": "computer-networks",
    "conceptTitle": "Computer Networks & Topologies",
    "subtitle": "CA453 Unit 1 Part 3 Academic Mastery",
    "summary": "In-depth analysis of computer networks & topologies covering foundational principles, system taxonomies, and architectural design.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca453",
    "subjectCode": "CA453",
    "subjectTitle": "C Programming",
    "unitId": "unit-1",
    "unitNumber": 1,
    "unitTitle": "Unit 1: Computer Fundamentals, Software, Networks & Internet Protocols",
    "conceptId": "internet-and-tcp-ip",
    "conceptTitle": "Internet Architecture & TCP/IP Model",
    "subtitle": "CA453 Unit 1 Part 4 Academic Mastery",
    "summary": "In-depth analysis of internet architecture & tcp/ip model covering foundational principles, system taxonomies, and architectural design.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca453",
    "subjectCode": "CA453",
    "subjectTitle": "C Programming",
    "unitId": "unit-2",
    "unitNumber": 2,
    "unitTitle": "Unit 2: UNIT 2 — OVERVIEW OF C LANGUAGE — CO2",
    "conceptId": "overview-of-c-language",
    "conceptTitle": "Overview of C Language",
    "subtitle": "CA453 Unit 2 Concept 1",
    "summary": "Comprehensive study notes covering Overview of C Language with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca453",
    "subjectCode": "CA453",
    "subjectTitle": "C Programming",
    "unitId": "unit-2",
    "unitNumber": 2,
    "unitTitle": "Unit 2: UNIT 2 — OVERVIEW OF C LANGUAGE — CO2",
    "conceptId": "data-types",
    "conceptTitle": "Data Types",
    "subtitle": "CA453 Unit 2 Concept 2",
    "summary": "Comprehensive study notes covering Data Types with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca453",
    "subjectCode": "CA453",
    "subjectTitle": "C Programming",
    "unitId": "unit-2",
    "unitNumber": 2,
    "unitTitle": "Unit 2: UNIT 2 — OVERVIEW OF C LANGUAGE — CO2",
    "conceptId": "assignment-operator",
    "conceptTitle": "Assignment Operator",
    "subtitle": "CA453 Unit 2 Concept 3",
    "summary": "Comprehensive study notes covering Assignment Operator with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca453",
    "subjectCode": "CA453",
    "subjectTitle": "C Programming",
    "unitId": "unit-3",
    "unitNumber": 3,
    "unitTitle": "Unit 3: UNIT 3: DECISION CONTROL STATEMENTS — CO3",
    "conceptId": "decision-control-statements",
    "conceptTitle": "Decision Control Statements",
    "subtitle": "CA453 Unit 3 Concept 1",
    "summary": "Comprehensive study notes covering Decision Control Statements with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca453",
    "subjectCode": "CA453",
    "subjectTitle": "C Programming",
    "unitId": "unit-3",
    "unitNumber": 3,
    "unitTitle": "Unit 3: UNIT 3: DECISION CONTROL STATEMENTS — CO3",
    "conceptId": "loops",
    "conceptTitle": "Loops",
    "subtitle": "CA453 Unit 3 Concept 2",
    "summary": "Comprehensive study notes covering Loops with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca453",
    "subjectCode": "CA453",
    "subjectTitle": "C Programming",
    "unitId": "unit-3",
    "unitNumber": 3,
    "unitTitle": "Unit 3: UNIT 3: DECISION CONTROL STATEMENTS — CO3",
    "conceptId": "array-declaration",
    "conceptTitle": "Array Declaration",
    "subtitle": "CA453 Unit 3 Concept 3",
    "summary": "Comprehensive study notes covering Array Declaration with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca453",
    "subjectCode": "CA453",
    "subjectTitle": "C Programming",
    "unitId": "unit-4",
    "unitNumber": 4,
    "unitTitle": "Unit 4: UNIT 4: FUNCTIONS — CO4",
    "conceptId": "functions",
    "conceptTitle": "Functions",
    "subtitle": "CA453 Unit 4 Concept 1",
    "summary": "Comprehensive study notes covering Functions with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca453",
    "subjectCode": "CA453",
    "subjectTitle": "C Programming",
    "unitId": "unit-4",
    "unitNumber": 4,
    "unitTitle": "Unit 4: UNIT 4: FUNCTIONS — CO4",
    "conceptId": "nesting-of-functions",
    "conceptTitle": "Nesting of Functions",
    "subtitle": "CA453 Unit 4 Concept 2",
    "summary": "Comprehensive study notes covering Nesting of Functions with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca453",
    "subjectCode": "CA453",
    "subjectTitle": "C Programming",
    "unitId": "unit-4",
    "unitNumber": 4,
    "unitTitle": "Unit 4: UNIT 4: FUNCTIONS — CO4",
    "conceptId": "pointer-arithmetic",
    "conceptTitle": "Pointer Arithmetic",
    "subtitle": "CA453 Unit 4 Concept 3",
    "summary": "Comprehensive study notes covering Pointer Arithmetic with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca453",
    "subjectCode": "CA453",
    "subjectTitle": "C Programming",
    "unitId": "unit-5",
    "unitNumber": 5,
    "unitTitle": "Unit 5: UNIT 5: STRUCTURE, UNION, ENUMERATION, MACROS AND FILE HANDLING — CO5",
    "conceptId": "structure-in-c",
    "conceptTitle": "Structure in C",
    "subtitle": "CA453 Unit 5 Concept 1",
    "summary": "Comprehensive study notes covering Structure in C with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca453",
    "subjectCode": "CA453",
    "subjectTitle": "C Programming",
    "unitId": "unit-5",
    "unitNumber": 5,
    "unitTitle": "Unit 5: UNIT 5: STRUCTURE, UNION, ENUMERATION, MACROS AND FILE HANDLING — CO5",
    "conceptId": "macros",
    "conceptTitle": "Macros",
    "subtitle": "CA453 Unit 5 Concept 2",
    "summary": "Comprehensive study notes covering Macros with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca453",
    "subjectCode": "CA453",
    "subjectTitle": "C Programming",
    "unitId": "unit-5",
    "unitNumber": 5,
    "unitTitle": "Unit 5: UNIT 5: STRUCTURE, UNION, ENUMERATION, MACROS AND FILE HANDLING — CO5",
    "conceptId": "fgetc",
    "conceptTitle": "fgetc()",
    "subtitle": "CA453 Unit 5 Concept 3",
    "summary": "Comprehensive study notes covering fgetc() with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca454",
    "subjectCode": "CA454",
    "subjectTitle": "Unix & Shell Programming",
    "unitId": "unit-1",
    "unitNumber": 1,
    "unitTitle": "Unit 1: UNIT 1: INTRODUCTION — CO1",
    "conceptId": "introduction-to-unix",
    "conceptTitle": "Introduction to UNIX",
    "subtitle": "CA454 Unit 1 Concept 1",
    "summary": "Comprehensive study notes covering Introduction to UNIX with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca454",
    "subjectCode": "CA454",
    "subjectTitle": "Unix & Shell Programming",
    "unitId": "unit-1",
    "unitNumber": 1,
    "unitTitle": "Unit 1: UNIT 1: INTRODUCTION — CO1",
    "conceptId": "chmod",
    "conceptTitle": "chmod",
    "subtitle": "CA454 Unit 1 Concept 2",
    "summary": "Comprehensive study notes covering chmod with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca454",
    "subjectCode": "CA454",
    "subjectTitle": "Unix & Shell Programming",
    "unitId": "unit-1",
    "unitNumber": 1,
    "unitTitle": "Unit 1: UNIT 1: INTRODUCTION — CO1",
    "conceptId": "write",
    "conceptTitle": "write()",
    "subtitle": "CA454 Unit 1 Concept 3",
    "summary": "Comprehensive study notes covering write() with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca454",
    "subjectCode": "CA454",
    "subjectTitle": "Unix & Shell Programming",
    "unitId": "unit-2",
    "unitNumber": 2,
    "unitTitle": "Unit 2: UNIT 2: UNIX SHELL PROGRAMMING — CO2",
    "conceptId": "unix-shell-programming",
    "conceptTitle": "UNIX Shell Programming",
    "subtitle": "CA454 Unit 2 Concept 1",
    "summary": "Comprehensive study notes covering UNIX Shell Programming with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca454",
    "subjectCode": "CA454",
    "subjectTitle": "Unix & Shell Programming",
    "unitId": "unit-2",
    "unitNumber": 2,
    "unitTitle": "Unit 2: UNIT 2: UNIX SHELL PROGRAMMING — CO2",
    "conceptId": "unix-environment",
    "conceptTitle": "UNIX Environment",
    "subtitle": "CA454 Unit 2 Concept 2",
    "summary": "Comprehensive study notes covering UNIX Environment with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca454",
    "subjectCode": "CA454",
    "subjectTitle": "Unix & Shell Programming",
    "unitId": "unit-2",
    "unitNumber": 2,
    "unitTitle": "Unit 2: UNIT 2: UNIX SHELL PROGRAMMING — CO2",
    "conceptId": "numeric-comparison-operators",
    "conceptTitle": "Numeric Comparison Operators",
    "subtitle": "CA454 Unit 2 Concept 3",
    "summary": "Comprehensive study notes covering Numeric Comparison Operators with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca454",
    "subjectCode": "CA454",
    "subjectTitle": "Unix & Shell Programming",
    "unitId": "unit-3",
    "unitNumber": 3,
    "unitTitle": "Unit 3: UNIT 3: PORTABILITY WITH C — CO3",
    "conceptId": "portability-with-c",
    "conceptTitle": "Portability with C",
    "subtitle": "CA454 Unit 3 Concept 1",
    "summary": "Comprehensive study notes covering Portability with C with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca454",
    "subjectCode": "CA454",
    "subjectTitle": "Unix & Shell Programming",
    "unitId": "unit-3",
    "unitNumber": 3,
    "unitTitle": "Unit 3: UNIT 3: PORTABILITY WITH C — CO3",
    "conceptId": "message-queues",
    "conceptTitle": "Message Queues",
    "subtitle": "CA454 Unit 3 Concept 2",
    "summary": "Comprehensive study notes covering Message Queues with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca454",
    "subjectCode": "CA454",
    "subjectTitle": "Unix & Shell Programming",
    "unitId": "unit-3",
    "unitNumber": 3,
    "unitTitle": "Unit 3: UNIT 3: PORTABILITY WITH C — CO3",
    "conceptId": "process-synchronization-with-wait",
    "conceptTitle": "Process Synchronization with wait()",
    "subtitle": "CA454 Unit 3 Concept 3",
    "summary": "Comprehensive study notes covering Process Synchronization with wait() with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca454",
    "subjectCode": "CA454",
    "subjectTitle": "Unix & Shell Programming",
    "unitId": "unit-4",
    "unitNumber": 4,
    "unitTitle": "Unit 4: UNIT 4: UNIX SYSTEM ADMINISTRATION — CO4",
    "conceptId": "unix-system-administration",
    "conceptTitle": "UNIX System Administration",
    "subtitle": "CA454 Unit 4 Concept 1",
    "summary": "Comprehensive study notes covering UNIX System Administration with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca454",
    "subjectCode": "CA454",
    "subjectTitle": "Unix & Shell Programming",
    "unitId": "unit-4",
    "unitNumber": 4,
    "unitTitle": "Unit 4: UNIT 4: UNIX SYSTEM ADMINISTRATION — CO4",
    "conceptId": "system-booting",
    "conceptTitle": "System Booting",
    "subtitle": "CA454 Unit 4 Concept 2",
    "summary": "Comprehensive study notes covering System Booting with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca454",
    "subjectCode": "CA454",
    "subjectTitle": "Unix & Shell Programming",
    "unitId": "unit-4",
    "unitNumber": 4,
    "unitTitle": "Unit 4: UNIT 4: UNIX SYSTEM ADMINISTRATION — CO4",
    "conceptId": "authorization",
    "conceptTitle": "Authorization",
    "subtitle": "CA454 Unit 4 Concept 3",
    "summary": "Comprehensive study notes covering Authorization with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca454",
    "subjectCode": "CA454",
    "subjectTitle": "Unix & Shell Programming",
    "unitId": "unit-5",
    "unitNumber": 5,
    "unitTitle": "Unit 5: UNIT 5: SHELL PROGRAMMING — CO5",
    "conceptId": "shell-programming",
    "conceptTitle": "Shell Programming",
    "subtitle": "CA454 Unit 5 Concept 1",
    "summary": "Comprehensive study notes covering Shell Programming with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca454",
    "subjectCode": "CA454",
    "subjectTitle": "Unix & Shell Programming",
    "unitId": "unit-5",
    "unitNumber": 5,
    "unitTitle": "Unit 5: UNIT 5: SHELL PROGRAMMING — CO5",
    "conceptId": "conditional-statements",
    "conceptTitle": "Conditional Statements",
    "subtitle": "CA454 Unit 5 Concept 2",
    "summary": "Comprehensive study notes covering Conditional Statements with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca454",
    "subjectCode": "CA454",
    "subjectTitle": "Unix & Shell Programming",
    "unitId": "unit-5",
    "unitNumber": 5,
    "unitTitle": "Unit 5: UNIT 5: SHELL PROGRAMMING — CO5",
    "conceptId": "error-redirection",
    "conceptTitle": "Error Redirection",
    "subtitle": "CA454 Unit 5 Concept 3",
    "summary": "Comprehensive study notes covering Error Redirection with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca455",
    "subjectCode": "CA455",
    "subjectTitle": "Software Engineering",
    "unitId": "unit-1",
    "unitNumber": 1,
    "unitTitle": "Unit 1: UNIT 1: FUNDAMENTAL CONCEPTS OF SOFTWARE ENGINEERING",
    "conceptId": "introduction-to-software-engineering",
    "conceptTitle": "Introduction to Software Engineering",
    "subtitle": "CA455 Unit 1 Concept 1",
    "summary": "Comprehensive study notes covering Introduction to Software Engineering with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca455",
    "subjectCode": "CA455",
    "subjectTitle": "Software Engineering",
    "unitId": "unit-1",
    "unitNumber": 1,
    "unitTitle": "Unit 1: UNIT 1: FUNDAMENTAL CONCEPTS OF SOFTWARE ENGINEERING",
    "conceptId": "software-design",
    "conceptTitle": "Software Design",
    "subtitle": "CA455 Unit 1 Concept 2",
    "summary": "Comprehensive study notes covering Software Design with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca455",
    "subjectCode": "CA455",
    "subjectTitle": "Software Engineering",
    "unitId": "unit-1",
    "unitNumber": 1,
    "unitTitle": "Unit 1: UNIT 1: FUNDAMENTAL CONCEPTS OF SOFTWARE ENGINEERING",
    "conceptId": "prototyping-model",
    "conceptTitle": "Prototyping Model",
    "subtitle": "CA455 Unit 1 Concept 3",
    "summary": "Comprehensive study notes covering Prototyping Model with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca455",
    "subjectCode": "CA455",
    "subjectTitle": "Software Engineering",
    "unitId": "unit-2",
    "unitNumber": 2,
    "unitTitle": "Unit 2: UNIT 2: SOFTWARE DESIGN",
    "conceptId": "software-design",
    "conceptTitle": "Software Design",
    "subtitle": "CA455 Unit 2 Concept 1",
    "summary": "Comprehensive study notes covering Software Design with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca455",
    "subjectCode": "CA455",
    "subjectTitle": "Software Engineering",
    "unitId": "unit-2",
    "unitNumber": 2,
    "unitTitle": "Unit 2: UNIT 2: SOFTWARE DESIGN",
    "conceptId": "structured-design-methodology",
    "conceptTitle": "Structured Design Methodology",
    "subtitle": "CA455 Unit 2 Concept 2",
    "summary": "Comprehensive study notes covering Structured Design Methodology with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca455",
    "subjectCode": "CA455",
    "subjectTitle": "Software Engineering",
    "unitId": "unit-2",
    "unitNumber": 2,
    "unitTitle": "Unit 2: UNIT 2: SOFTWARE DESIGN",
    "conceptId": "relationships-among-objects",
    "conceptTitle": "Relationships Among Objects",
    "subtitle": "CA455 Unit 2 Concept 3",
    "summary": "Comprehensive study notes covering Relationships Among Objects with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca455",
    "subjectCode": "CA455",
    "subjectTitle": "Software Engineering",
    "unitId": "unit-3",
    "unitNumber": 3,
    "unitTitle": "Unit 3: UNIT 3: SOFTWARE CODING",
    "conceptId": "software-coding",
    "conceptTitle": "Software Coding",
    "subtitle": "CA455 Unit 3 Concept 1",
    "summary": "Comprehensive study notes covering Software Coding with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca455",
    "subjectCode": "CA455",
    "subjectTitle": "Software Engineering",
    "unitId": "unit-3",
    "unitNumber": 3,
    "unitTitle": "Unit 3: UNIT 3: SOFTWARE CODING",
    "conceptId": "testing-objectives",
    "conceptTitle": "Testing Objectives",
    "subtitle": "CA455 Unit 3 Concept 2",
    "summary": "Comprehensive study notes covering Testing Objectives with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca455",
    "subjectCode": "CA455",
    "subjectTitle": "Software Engineering",
    "unitId": "unit-3",
    "unitNumber": 3,
    "unitTitle": "Unit 3: UNIT 3: SOFTWARE CODING",
    "conceptId": "alpha-testing",
    "conceptTitle": "Alpha Testing",
    "subtitle": "CA455 Unit 3 Concept 3",
    "summary": "Comprehensive study notes covering Alpha Testing with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca455",
    "subjectCode": "CA455",
    "subjectTitle": "Software Engineering",
    "unitId": "unit-4",
    "unitNumber": 4,
    "unitTitle": "Unit 4: UNIT 4: SOFTWARE TESTING AND QUALITY ASSURANCE",
    "conceptId": "software-quality",
    "conceptTitle": "Software Quality",
    "subtitle": "CA455 Unit 4 Concept 1",
    "summary": "Comprehensive study notes covering Software Quality with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca455",
    "subjectCode": "CA455",
    "subjectTitle": "Software Engineering",
    "unitId": "unit-4",
    "unitNumber": 4,
    "unitTitle": "Unit 4: UNIT 4: SOFTWARE TESTING AND QUALITY ASSURANCE",
    "conceptId": "lines-of-code",
    "conceptTitle": "Lines of Code",
    "subtitle": "CA455 Unit 4 Concept 2",
    "summary": "Comprehensive study notes covering Lines of Code with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca455",
    "subjectCode": "CA455",
    "subjectTitle": "Software Engineering",
    "unitId": "unit-4",
    "unitNumber": 4,
    "unitTitle": "Unit 4: UNIT 4: SOFTWARE TESTING AND QUALITY ASSURANCE",
    "conceptId": "software-quality-standards",
    "conceptTitle": "Software Quality Standards",
    "subtitle": "CA455 Unit 4 Concept 3",
    "summary": "Comprehensive study notes covering Software Quality Standards with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca456",
    "subjectCode": "CA456",
    "subjectTitle": "Operating System",
    "unitId": "unit-1",
    "unitNumber": 1,
    "unitTitle": "Unit 1: UNIT 1: INTRODUCTION",
    "conceptId": "operating-system-definition",
    "conceptTitle": "Operating System: Definition",
    "subtitle": "CA456 Unit 1 Concept 1",
    "summary": "Comprehensive study notes covering Operating System: Definition with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca456",
    "subjectCode": "CA456",
    "subjectTitle": "Operating System",
    "unitId": "unit-1",
    "unitNumber": 1,
    "unitTitle": "Unit 1: UNIT 1: INTRODUCTION",
    "conceptId": "io-management",
    "conceptTitle": "I/O Management",
    "subtitle": "CA456 Unit 1 Concept 2",
    "summary": "Comprehensive study notes covering I/O Management with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca456",
    "subjectCode": "CA456",
    "subjectTitle": "Operating System",
    "unitId": "unit-1",
    "unitNumber": 1,
    "unitTitle": "Unit 1: UNIT 1: INTRODUCTION",
    "conceptId": "cooperating-processes",
    "conceptTitle": "Cooperating Processes",
    "subtitle": "CA456 Unit 1 Concept 3",
    "summary": "Comprehensive study notes covering Cooperating Processes with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca456",
    "subjectCode": "CA456",
    "subjectTitle": "Operating System",
    "unitId": "unit-2",
    "unitNumber": 2,
    "unitTitle": "Unit 2: UNIT 2: CPU SCHEDULING AND PROCESS SYNCHRONIZATION",
    "conceptId": "cpu-scheduling",
    "conceptTitle": "CPU Scheduling",
    "subtitle": "CA456 Unit 2 Concept 1",
    "summary": "Comprehensive study notes covering CPU Scheduling with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca456",
    "subjectCode": "CA456",
    "subjectTitle": "Operating System",
    "unitId": "unit-2",
    "unitNumber": 2,
    "unitTitle": "Unit 2: UNIT 2: CPU SCHEDULING AND PROCESS SYNCHRONIZATION",
    "conceptId": "critical-section-problem",
    "conceptTitle": "Critical Section Problem",
    "subtitle": "CA456 Unit 2 Concept 2",
    "summary": "Comprehensive study notes covering Critical Section Problem with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca456",
    "subjectCode": "CA456",
    "subjectTitle": "Operating System",
    "unitId": "unit-2",
    "unitNumber": 2,
    "unitTitle": "Unit 2: UNIT 2: CPU SCHEDULING AND PROCESS SYNCHRONIZATION",
    "conceptId": "readers-writers-problem",
    "conceptTitle": "Readers-Writers Problem",
    "subtitle": "CA456 Unit 2 Concept 3",
    "summary": "Comprehensive study notes covering Readers-Writers Problem with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca456",
    "subjectCode": "CA456",
    "subjectTitle": "Operating System",
    "unitId": "unit-3",
    "unitNumber": 3,
    "unitTitle": "Unit 3: UNIT 3: DEADLOCK AND STORAGE MANAGEMENT",
    "conceptId": "deadlock",
    "conceptTitle": "Deadlock",
    "subtitle": "CA456 Unit 3 Concept 1",
    "summary": "Comprehensive study notes covering Deadlock with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca456",
    "subjectCode": "CA456",
    "subjectTitle": "Operating System",
    "unitId": "unit-3",
    "unitNumber": 3,
    "unitTitle": "Unit 3: UNIT 3: DEADLOCK AND STORAGE MANAGEMENT",
    "conceptId": "process-termination",
    "conceptTitle": "Process Termination",
    "subtitle": "CA456 Unit 3 Concept 2",
    "summary": "Comprehensive study notes covering Process Termination with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca456",
    "subjectCode": "CA456",
    "subjectTitle": "Operating System",
    "unitId": "unit-3",
    "unitNumber": 3,
    "unitTitle": "Unit 3: UNIT 3: DEADLOCK AND STORAGE MANAGEMENT",
    "conceptId": "worst-fit",
    "conceptTitle": "Worst Fit",
    "subtitle": "CA456 Unit 3 Concept 3",
    "summary": "Comprehensive study notes covering Worst Fit with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca456",
    "subjectCode": "CA456",
    "subjectTitle": "Operating System",
    "unitId": "unit-4",
    "unitNumber": 4,
    "unitTitle": "Unit 4: UNIT 4: VIRTUAL MEMORY AND FILE MANAGEMENT",
    "conceptId": "demand-paging",
    "conceptTitle": "Demand Paging",
    "subtitle": "CA456 Unit 4 Concept 1",
    "summary": "Comprehensive study notes covering Demand Paging with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca456",
    "subjectCode": "CA456",
    "subjectTitle": "Operating System",
    "unitId": "unit-4",
    "unitNumber": 4,
    "unitTitle": "Unit 4: UNIT 4: VIRTUAL MEMORY AND FILE MANAGEMENT",
    "conceptId": "page-size-considerations",
    "conceptTitle": "Page Size Considerations",
    "subtitle": "CA456 Unit 4 Concept 2",
    "summary": "Comprehensive study notes covering Page Size Considerations with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  },
  {
    "degreeId": "mca",
    "degreeName": "MCA",
    "semesterId": "sem1",
    "semesterNumber": 1,
    "subjectId": "ca456",
    "subjectCode": "CA456",
    "subjectTitle": "Operating System",
    "unitId": "unit-4",
    "unitNumber": 4,
    "unitTitle": "Unit 4: UNIT 4: VIRTUAL MEMORY AND FILE MANAGEMENT",
    "conceptId": "tree-structured-directory",
    "conceptTitle": "Tree-Structured Directory",
    "subtitle": "CA456 Unit 4 Concept 3",
    "summary": "Comprehensive study notes covering Tree-Structured Directory with full theoretical rigor, proofs, diagrams, and code implementations.",
    "quizCount": 3,
    "flashcardCount": 4
  }
];

export default searchIndex;
